#include "interpreter.h"
#include "core/random.h"

namespace tempearly
{
    /**
     * Bool.rand() => Bool
     *
     * Returns boolean value generated by the random number generator included
     * with the interpreter.
     */
    TEMPEARLY_NATIVE_METHOD(bool_s_rand)
    {
        return Value::NewBool(Random::NextBool());
    }

    /**
     * Bool#__str__() => String
     *
     * Returns string representation of the boolean object, either "true" or
     * "false".
     */
    TEMPEARLY_NATIVE_METHOD(bool_str)
    {
        return Value::NewString(args[0].AsBool() ? "true" : "false");
    }

    void init_bool(Interpreter* i)
    {
        i->cBool = i->AddClass("Bool", i->cObject);

        i->cBool->AddStaticMethod(i, "rand", 0, bool_s_rand);

        i->cBool->AddMethod(i, "__str__", 0, bool_str);
    }
}
